### ISSUE TITLE
LRM: grammar for sequence comprehensions is wrong

### ISSUE THREAD

**Issue by peterwvj** [overturetool/documentation#17]
As described in https://github.com/overturetool/overture/issues/692 there's a problem with the grammar for sequence comprehensions. As pointed out by @nickbattle :

> The sequence bind can bind multiple variables, but it can only do so via a simple bind, so that the > sequence is defined. So for example, you can say:

>```
>[ a+b | mk_(a, b) in seq [...] ]
>```
>But you cannot say:
>```
>[ a+b | a, b in seq [...] ]
>```

But this constraint is not reflected by the LRM. This needs to be fixed.

**Comment by nickbattle** [comment]
Currently, the LRM grammar says that a sequence comprehension includes a "bind list", which is a list of *multiple* binds. This is wrong. Note that the old (pre "in seq") form allowed only a "set bind", with a caveat in the text that it must only bind a single numeric variable.

So in the "in seq" world, a sequence comprehension is either a single "set bind" that binds a single variable, in a single pattern, to an *ordered* type (not necessarily numeric), or it is a single "seq bind" that can bind arbitrarily many variables, in one pattern, of ordered or non-ordered types (because the order comes from the sequence passed to the bind).

So in section 6.8, we want `sequence comprehension = '[', expression, '|', set bind | seq bind, [ '&', expression ], ']'

The text in 6.8 about sequence comprehensions over sequences has to be corrected to say that it can bind as many variables as it likes in the one pattern, rather than just one.

The text in 6.8 about sequence comprehensions over sets is correct. It says that there is only one variable and that must be to a value of an ordered type.

The grammar change also has to be reflected in section A.5.9.

**Comment by peterwvj** [comment]
Thanks, Nick. Are you happy with the changes?

https://github.com/overturetool/documentation/blob/editing/documentation/VDM10LangMan/VDM10_lang_man.pdf

**Comment by nickbattle** [comment]
That looks perfect! Thanks PJ.

**Comment by nickbattle** [comment]
I think this is still wrong in the LRM.

One of PGL's students raised a problem today because he was expecting to be able to use a type bind with a sequence comprehension. This ought to be permitted, if the type is ordered and (for the interpreter) finite - though Overture has the minint/maxint feature that would allow limited type bind evaluation for nat/int.

I think the grammar should be similar to the bind in exists1 and iota; that is, it should just be "bind" which can be a set, sequence or type bind. Separately, there is a type check that the patterns concerned for set and type binds only have one (ordered) variable, while seq binds can have multiple variables (and the order is taken from the seq).
```
sequence comprehension = ‘[’, expression, ‘|’, bind, [ ‘&’, expression ], ‘]’ ;
```

Both VDMJ and Overture were parsing seq comprehensions with set/seq binds only. I've prepared code changes for this.

**Comment by tomooda** [comment]
done by https://github.com/overturetool/documentation/commit/3535b5c68abff3214e361b680e042f44ae3efd11 .
