### ISSUE TITLE
Conway Game of Life Example not working

### ISSUE THREAD

**Issue by ldcouto** [overturetool/documentation#2]
The graphical version of the Conway example does not work.

This is because the jar is not a part of the example -- only the Java sources.

**Comment by peterwvj** [comment]
I think all the examples need a more thorough cleanup. There are other models with invalid launch configurations and the BuslinesPP model (GUI) has never worked. It's suppose to be replaced by BuslinesWithDBPP, which currently can't be executed due to issue #452 (overture). This model in particular is used in the TiMoMi course.

So we could change this issue to include a more thorough check of the SL, PP and RT models. This might include fixing type errors in some models, fixing launch configurations etc. I know @miranha  has been working a bit with the examples packaging so I think we should put him on the task so he can get more involved in the development.

**Comment by ldcouto** [comment]
Sounds like a good idea to me.

**Comment by peterwvj** [comment]
I was browsing the examples and I was only able to find an SL version of the Conway model. It did not use the GUI feature and it executed without any errors. Maybe you confuse it with one of the other GUI models?

@miranha Have you looked into some of the issues with the `.jar` based models?

**Comment by ldcouto** [comment]
I'm pretty sure the Conway model is SL only.

The gui stuff is  a custom jar that visualises the population.  There
should be some Java classes there.

**Comment by nickbattle** [comment]
Yes, Conway is SL only - who needs stinking objects anyway? :)  And yes, there is a GUI - it is a simple Java Applet that calls back to the model to update a grid of points. I haven't checked, but it wouldn't surprise me if the Java jar isn't in the examples repository. But the model works fine without the Java animation.

**Comment by peterwvj** [comment]
Hehe :)

According to the README the model has multiple entry points. The default entry points does not seem to use the animation feature. However, if you execute `gui_Graphics``generations_animate(130, DIEHARD)` you get the following error:

`Error 4024: 'not yet specified' expression reached in 'gui_Graphics' (.../Graphics.vdmsl) at line 39:42`\

Se yes you are both right :)

**Comment by ldcouto** [comment]
Yes, Peter, I know :) 

The sources are there: https://github.com/overturetool/documentation/tree/editing/examples/VDMSL/ConwayGameLife/src

It's just a matter of generating the jar and bundling it in.

**Comment by peterwvj** [comment]
Yes I build a jar and tested it :) The GUI loads and it starts drawing figures in a grid. I will try to get the `.jar` file committed.

**Comment by peterwvj** [comment]
I checked out the `pvj/pureoperations` branch and built Overture. I was able to import the Conway example and run it with the GUI. I'll leave the issue open so we don't forget to check that the example works once the release candidate is out.

**Comment by ldcouto** [comment]
Great job, guy.

**Comment by peterwvj** [comment]
The example now works in 2.3.0 so I'll close this issue
